#!/bin/bash
MASTER=yarn
DEPLOY_MODE=cluster
JAR_FILE=/home/hadoop/code/spark/MySpark/build/libs/MySpark.jar

# Cleanup
hdfs dfs -rm -r /outputs/RealEstate

# Submit
spark-submit --class com.rueggerllc.spark.apps.AverageHousePrice --master $MASTER --deploy-mode $DEPLOY_MODE $JAR_FILE $*


# Get Output
hdfs dfs -get /outputs/RealEstate ./Output
cat ./Output/part*
