#!/bin/bash

MASTER=local[*]
APP=com.rueggerllc.spark.streaming.TemperatureConsumer
FATJARFILE=/home/hadoop/code/spark/SparkStreaming/build/libs/SparkStreaming-fat-1.0.jar

# Submit
spark-submit --class $APP --master $MASTER $FATJARFILE
