#!/bin/bash

MASTER=local[*]
FATJARFILE=/home/hadoop/code/spark/SparkStreaming/build/libs/SparkStreaming-all-1.0.jar

# Submit
spark-submit --class com.rueggerllc.spark.streaming.KafkaConsumer --master $MASTER $FATJARFILE
