#!/bin/bash
MASTER=yarn
DEPLOY_MODE=cluster
JAR_FILE=/home/hadoop/code/spark/SparkStreaming/build/libs/SparkStreaming.jar

# Submit
spark-submit --class com.rueggerllc.spark.apps.StreamingWordCount --master $MASTER \
             --deploy-mode $DEPLOY_MODE $JAR_FILE $*
