#!/bin/bash

MASTER=local[*]
JAR_FILE=/home/hadoop/code/spark/SparkStreaming/build/libs/SparkStreaming.jar


# Submit
spark-submit --class com.rueggerllc.spark.streaming.KafkaConsumer --master $MASTER $JAR_FILE $HOST $PORT
